name: celerite

channels:
  - conda-forge

dependencies:
  - python=3.5
  - numpy
  - eigen
  - pybind11
  - pip:
      - https://github.com/michaeljones/breathe/zipball/d3eae7fac4d2ead062070fd149ec8bf839f74ed5
